services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polochan-api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev