export const envSchema = {
  type: 'object',
  required: [
    'NODE_ENV',
    'LOG_LEVEL',
    'PORT',
    'HOST',
    'POSTGRES_HOST',
    'POSTGRES_PORT',
    'POSTGRES_USER',
    'POSTGRES_PASSWORD',
    'POSTGRES_DB',
    'MONGODB_URI',
    'MONGODB_PORT',
    'MONGO_INITDB_ROOT_USERNAME',
    'MONGO_INITDB_ROOT_PASSWORD',
    'FRONTEND_URL',
    'JWT_SECRET',
  ],
  properties: {
    NODE_ENV: { type: 'string' },
    LOG_LEVEL: { type: 'string' },
    PORT: { type: 'string' },
    HOST: { type: 'string' },
    POSTGRES_HOST: { type: 'string' },
    POSTGRES_PORT: { type: 'string' },
    POSTGRES_USER: { type: 'string' },
    POSTGRES_PASSWORD: { type: 'string' },
    POSTGRES_DB: { type: 'string' },
    MONGODB_URI: {
      type: 'string',
    },
    MONGODB_PORT: { type: 'string' },
    MONGO_INITDB_ROOT_USERNAME: { type: 'string' },
    MONGO_INITDB_ROOT_PASSWORD: { type: 'string' },
    FRONTEND_URL: { type: 'string' },
    JWT_SECRET: { type: 'string' },
  },
};
