export const envSchema = {
  type: 'object',
  required: [
    'NODE_ENV',
    'LOG_LEVEL',
    'PORT',
    'HOST',
    'POSTGRES_HOST',
    'POSTGRES_PORT',
    'POSTGRES_USER',
    'POSTGRES_PASSWORD',
    'POSTGRES_DB',
    'MONGODB_URI',
    'MONGODB_PORT',
    'MONGO_INITDB_ROOT_USERNAME',
    'MONGO_INITDB_ROOT_PASSWORD',
  ],
  properties: {
    NODE_ENV: { type: 'string', default: 'development' },
    LOG_LEVEL: { type: 'string', default: 'info' },
    PORT: { type: 'string', default: '3000' },
    HOST: { type: 'string', default: '0.0.0.0' },
    POSTGRES_HOST: { type: 'string', default: 'localhost' },
    POSTGRES_PORT: { type: 'string', default: '5443' },
    POSTGRES_USER: { type: 'string', default: 'polichan_user' },
    POSTGRES_PASSWORD: { type: 'string', default: 'polichan_uwu' },
    POSTGRES_DB: { type: 'string', default: 'polichan_db' },
    MONGODB_URI: {
      type: 'string',
      default: 'mongodb://localhost:27017/polichan_db',
    },
    MONGODB_PORT: { type: 'string', default: '27027' },
    MONGO_INITDB_ROOT_USERNAME: { type: 'string', default: 'polichan_user' },
    MONGO_INITDB_ROOT_PASSWORD: { type: 'string', default: 'polichan_uwu' },
  },
};
